data:
  train_file: data/newssumm_processed/newssumm_processed.json
  max_input_length: 2048
  max_target_length: 256
  val_split: 0.01

experiment:
  name: flan_t5_xxl_run_001
  output_dir: results/flan_t5_xxl_run_001

model:
  name: google/flan-t5-xxl
  family: flan_t5
  type: seq2seq

system:
  device: auto

training:
  batch_size: 1
  epochs: 1
  fp16: true
  learning_rate: 1e-5
  seed: 42              # ACTUAL GPU batch
  gradient_accumulation_steps: 8  # makes effective batch = 8
  max_train_samples: 100
